version: '3.8'

services:
  yugabytedb:
    image: yugabytedb/yugabyte:2.25.2.0-b359
    container_name: haddi_yugabytedb
    restart: unless-stopped
    ports:
      - "5433:5433"
      - "7005:7000"
      - "9000:9000"
    command:
      [
        "/home/yugabyte/bin/yugabyted",
        "start",
        "--daemon=false",
        "--tserver_flags=ysql_yb_enable_advisory_locks=true,allowed_preview_flags_csv=ysql_yb_enable_advisory_locks"
      ]
    volumes:
      - yb_data:/home/yugabyte/var
    networks:
      - haddi_network

  yugabytedb-init:
    image: yugabytedb/yugabyte:2.25.2.0-b359
    container_name: haddi_yugabytedb_init
    depends_on:
      - yugabytedb
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 10 &&
      ysqlsh -h yugabytedb -p 5433 -U yugabyte -d yugabyte -c \"\
        DO $$\
        BEGIN\
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'haddi_user') THEN\
            CREATE USER haddi_user WITH PASSWORD 'haddi_password';\
          END IF;\
        END$$;\
        CREATE DATABASE haddi_db OWNER haddi_user;\
        GRANT ALL PRIVILEGES ON DATABASE haddi_db TO haddi_user;\
      \" || true"
    networks:
      - haddi_network

  redis:
    image: redis:7-alpine
    container_name: haddi_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - haddi_network
    command: redis-server --appendonly yes --save 900 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haddi_app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4545
      DATABASE_URL: postgresql://yugabyte:yugabyte@yugabytedb:5433/yugabyte
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_here_change_in_production
      EMAIL_USER: naman.patna@gmail.com
      EMAIL_PASS: ${EMAIL_PASS:-your_email_password_here}
      GOOGLE_CLIENT_ID: your_google_client_id_here
      GOOGLE_CLIENT_SECRET: your_google_client_secret_here
    ports:
      - "4545:4545"
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      yugabytedb-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - haddi_network
    command: npm start

volumes:
  yb_data:
    driver: local
  redis_data:
    driver: local

networks:
  haddi_network:
    driver: bridge 